spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: "jdbc:postgresql://localhost:5432/stage2module4db?createDatabaseIfNotExist=true"
    username: user
    password: password
#  jpa:
#    show-sql: true

#    hibernate:
#      ddl-auto: update

logging:
  level:
    com.epam.esm.epammodule4.service: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
#    root: DEBUG

app:
  initial-data:
    records: 0

  jwtSecret: "SuperSecretKey"
#  jwtExpirationMs: 60000
#  jwtRefreshExpirationMs: 120000
