server:
  port: 8081

  tomcat:
    relaxed-path-chars: '|,{,},[,],\'
    relaxed-query-chars: '|,{,},[,],\'

spring:
  profiles:
    active: "dev"

  application:
    name: gift certificates

  data:
    web:
      pageable:
        default-page-size: 10
    rest:
      default-page-size:

  config:
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect

    properties:
      hibernate:
        jdbc:
          time_zone: UTC

app:
  initial-data:
    records: 0

  jwtSecret: "SuperSecretKey"
  jwtExpirationMs: 3600000
#  jwtExpirationMs: 10000
  jwtRefreshExpirationMs: 86400000

  use-oauth2:
    false

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
          - env
          - info
          - metrics
          - mappings
